;; spawn_kernel.wat
;;
;; Example kernel that imports env.log and env.spawn.
;; When run(ptr, len) is called, it first echoes the source back via log
;; and then passes the same blob to spawn, asking the bootloader to create
;; a sibling instance.
;;
;; Build:
;;   wat2wasm spawn_kernel.wat -o spawn_kernel.wasm
;;   base64 spawn_kernel.wasm   # paste result as SPAWN_KERNEL_GLOB in constants.h
;;
;; Pre-encoded base64 (generated by scripts; see constants.h SPAWN_KERNEL_GLOB):
;;   AGFzbQEAAAABBgFgAn9/AAIXAgNlbnYDbG9nAAADZW52BXNwYXduAAADAgEABQMBAAEHEAIGbWVtb3J5AgADcnVuAAIKEAEOACAAIAEQACAAIAEQAQs=

(module
  ;; Single type: (func (param i32 i32))
  (type $t0 (func (param i32 i32)))

  ;; Host imports
  (import "env" "log"   (func $log   (type $t0)))
  (import "env" "spawn" (func $spawn (type $t0)))

  ;; Linear memory (1 page = 64 KiB); host writes the quine here
  (memory (export "memory") 1)

  ;; run(ptr:i32, len:i32) – entry point called by the bootloader
  (func (export "run") (param $ptr i32) (param $len i32)
    ;; Echo source back to host log
    (call $log   (local.get $ptr) (local.get $len))
    ;; Request a new sibling instance with the same genome
    (call $spawn (local.get $ptr) (local.get $len))
  )
)
